#error
ID_WRONG_BOOK = 0
ID_WRONG_USER = 1
ID_WRONG_DATE = 2
USER_EXISTS = 3
RES_WRONG_USER = 4
RES_WRONG_DATE = 5
RES_WRONG_BOOK = 6
RES_NO_BOOKS = 7
RES_NOT_EXISTS = 8
RES_USER_NOT_EXISTS = 9

#info
INCL_DATE = 10
NOT_INCL_DATE = 11
RES_OVERLAP = 12
RES_NOT_OVERLAP = 13
RES_ID_VALID = 14
RES_CHG_FOR = 15
USER_CREATED = 16
BOOK_ADDED = 17
RES_INCLUDED = 18
RES_EXISTS = 19
RES_CHG_TO = 20
LIB_CREATED = 21
RES_CREATED = 22
